version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: template
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    networks:
      - devnet
    volumes:
      - mongo_data:/data/db

networks:
  devnet:

volumes:
  mongo_data:
